# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [4]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [8]:
a = np.random.randint( 1, 4 , 100)
b = np.random.randint( 1, 3 , 100)
c = np.random.randint( 10000 , 30000 , 100)

In [9]:
a

array([2, 1, 2, 3, 1, 3, 2, 1, 1, 2, 2, 2, 1, 3, 3, 2, 1, 3, 2, 3, 2, 2,
       2, 3, 2, 1, 2, 2, 3, 2, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 3, 3, 1,
       2, 1, 1, 1, 2, 2, 2, 3, 1, 2, 3, 1, 2, 1, 2, 1, 3, 1, 1, 2, 3, 2,
       2, 1, 1, 3, 1, 1, 1, 3, 3, 2, 1, 2, 3, 2, 1, 3, 2, 2, 3, 1, 1, 1,
       2, 1, 3, 1, 3, 2, 1, 2, 2, 2, 1, 2])

In [10]:
b

array([2, 2, 2, 1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2,
       1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2,
       1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 1, 2,
       2, 1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1, 1, 1,
       1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2])

In [11]:
c

array([27572, 24322, 16900, 14236, 28035, 23182, 12837, 18317, 14984,
       23026, 12981, 10057, 19712, 28154, 11905, 17181, 26732, 17713,
       18559, 13842, 12341, 18966, 28624, 10544, 12940, 19699, 13919,
       20089, 28684, 18852, 23888, 23930, 28238, 17155, 17572, 22552,
       14078, 16499, 24231, 12936, 28230, 16890, 21139, 10191, 25983,
       21088, 12783, 26846, 19744, 19898, 26239, 18172, 21083, 20463,
       10699, 17346, 24921, 27588, 23771, 29303, 24437, 23498, 29969,
       21228, 10457, 14344, 29059, 29314, 21343, 29204, 16939, 12200,
       27195, 10281, 24313, 28713, 11826, 28963, 15419, 19227, 26923,
       24024, 27737, 28845, 15931, 16030, 24510, 16981, 18048, 29323,
       21376, 29214, 11529, 18353, 10064, 21052, 19299, 10006, 26876,
       10273])

### Step 3. Let's create a DataFrame by joinning the Series by column

In [17]:
a = pd.DataFrame(a)
b = pd.DataFrame(b)
c = pd.DataFrame(c)

In [18]:
abc = pd.concat([a, b, c], axis=1)

In [19]:
abc

0  0      0
0   2  2  27572
1   1  2  24322
2   2  2  16900
3   3  1  14236
4   1  1  28035
.. .. ..    ...
95  2  1  21052
96  2  1  19299
97  2  1  10006
98  1  2  26876
99  2  2  10273

[100 rows x 3 columns]

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [20]:
abc.columns = ['bedrs', 'bathrs', 'price_sqr_meter']

In [21]:
abc

bedrs  bathrs  price_sqr_meter
0       2       2            27572
1       1       2            24322
2       2       2            16900
3       3       1            14236
4       1       1            28035
..    ...     ...              ...
95      2       1            21052
96      2       1            19299
97      2       1            10006
98      1       2            26876
99      2       2            10273

[100 rows x 3 columns]

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [27]:
bigcolumn = pd.concat([a, b, c], axis=0)

In [32]:
bigcolumn

0
0       2
1       1
2       2
3       3
4       1
..    ...
95  21052
96  19299
97  10006
98  26876
99  10273

[300 rows x 1 columns]

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [30]:
#Como é possível ver abaixo o bigcolumn tem 300 entradas. 
#Entretanto, quando juntamos os 3 dataframes o índeces não foram alterados
bigcolumn.shape

(300, 1)

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [38]:
bigcolumn.reset_index(drop=True)

0
0        2
1        1
2        2
3        3
4        1
..     ...
295  21052
296  19299
297  10006
298  26876
299  10273

[300 rows x 1 columns]